sudo: required
services:
  - docker

before_install:
  - docker build -t sumitchandnani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sumitchandnani/docker-react npm run test -- --coverage